In [1]:
print("Hello World")

Hello World


In [2]:
print("Python을 시작합니다\n안녕하세요?")

Python을 시작합니다
안녕하세요?


In [3]:
pi=3.14159265
print(pi)

3.14159265


In [5]:
print("원주율은 {a}이고, 근사치로는 {b:.2f}입니다". format(a=pi, b=pi))

원주율은 3.14159265이고, 근사치로는 3.14입니다


In [6]:
type(10) #정수형

int

In [7]:
type(3.14) #실수형

float

## 문자열(string)

In [12]:
C3 = "Life"
C4 = "is"
C5 = "too"
C6 = "short"
C7 = C3 + C4 + C5 + C6 
C8 = C3 + " " + C4 + " " + C5 + " " + C6
print(C7)
print(C8)
# " " 띄어쓰기

Lifeistooshort
Life is too short


In [16]:
D1 = "Hello python"
D2 = "안녕하세요 파이썬씨? 우리 잘 해봅시다"
print(D1[0]) # D1에서 첫 번째 문자
print(D2[-1]) # D2 끝에서 첫 번째 문자
print(D2[3:5]) # D2 4~5번째 문자

H
다
세요


In [20]:
print(D2.find('파'))# 0부터 시작, 공백 감안
print(D2.index('파'))
print(D2.find('카'))
#print(D2.index('카')) 
#find에서는 없는 문자를 찾으라는 명령에 -1을 output하는 것과 달리 index는 없는 문자를 찾으라는 명령에는 에러가 뜸

6
6
-1


In [26]:
C9 = " Hello "
print(C9)
print(C9.lstrip())
print(C9.rstrip())
print(C9.strip())


 Hello 
Hello 
 Hello
Hello


In [28]:
C10 = "한국대학교"
print(C10.replace("한국","동국"))
#replace("a","b")  : a를 b로 변환

동국대학교


In [30]:
C11 = "동국v대학교"
print(C11.split("v"))
#v를 기준으로 나누기

['동국', '대학교']


## 목록과 튜플

In [38]:
L1 = [1,2,3,4]
L2 = ['Life', 'is', 'too', 'short']
L3 = [1,2,'Python']
L4 = [1,2,['Life', 'Python']]

print(L1[0])
print(L4[-1][0])

1
Life


In [39]:
L4.append('g')
print(L4)
# append: 기존의 요소에 새로운 요소 추가

[1, 2, ['Life', 'Python'], 'g']


In [41]:
L1.insert(2,5)
print(L1)
# insert(a,b) : a 위치에 b 삽입

[1, 2, 5, 3, 4]


In [42]:
L3 + L4

[1, 2, 'Python', 1, 2, ['Life', 'Python'], 'g']

In [47]:
# 요소 값 수정
L6 = [1,2,3,5,4,6,7]
L6[3:5]= [4,5]
print(L6)

[1, 2, 3, 4, 5, 6, 7]


In [48]:
# 특정 요소 삭제: del

del L6[6]
print(L6)


[1, 2, 3, 4, 5, 6]


In [49]:
L7 = [1,1,1,1,1,2,1,1,1,1,1,1,3,3,4,4,5,5,1,1,1,1,1,1,4]
print(L7.count(1))
# L7에서 1이 몇개인지 카운팅

17


In [51]:
L7.sort()
print(L7)
# 오름차순 정렬

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 3, 4, 4, 4, 5, 5]


In [52]:
L7.sort(reverse=True)
print(L7)

[5, 5, 4, 4, 4, 3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


### T1 = (1,2,3,4,5)  : 튜플 형태
### 튜플은 목록형 데이터와는 달리 수정이 불가능

## 사전(dictionary)

In [ ]:
# 사전은 데이터에 key와 value가 key:value 형태로 표시됨

In [54]:
D11 = {'name':'KIM','birth':'2003','height':'175'}
print(D11['name'])

KIM


In [57]:
#D11에 새로운 key와 value 추가
D11['weight']='60'
print(D11)
print(D11['weight'])

{'name': 'KIM', 'birth': '2003', 'height': '175', 'weight': '60'}
60


In [58]:
D11key = list(D11.keys())
print(D11key)
# key list 만들기

['name', 'birth', 'height', 'weight']


In [59]:
D11value = list(D11.values())
print(D11value)

['KIM', '2003', '175', '60']


## 다차원배열(ndarray)

In [61]:
import numpy as np
V1 = np.array([1,2,3,4])
print(V1)

[1 2 3 4]


In [64]:
V2 = np.arange(5)
print(V2)

[0 1 2 3 4]


In [65]:
V3 = np.arange(1,10,2)*2
print(V3)

[ 2  6 10 14 18]


In [ ]:
~~

In [ ]:
~~

In [ ]:
~~

## 제어문

In [67]:
# 조건문 if
금액 = 5000
if 금액 == 5000:
    print("짜장면")

짜장면


In [68]:
금액 = 6000
if 금액==5000:
    print("짜장면")
if 10000>금액>5000:
    print("짬뽕")
    
## if를 두번 쓰는 경우 vs if와 elif를 쓰는 경우
# 전자는 두 개의 조건을 모두 검토, 후자의 경우는 첫 번째 조건을 만족하면 두 번째 조건은 검토하지 않음.

짬뽕


In [69]:
금액= 4000
if 금액==5000:
    print("짜장면")
elif 10000>금액>5000:
    print("짬뽕")
else:
    print("죄송해요")

죄송해요


In [ ]:
# if ... elif

In [70]:
음식메뉴 = ['짜장면','짬뽕']
if '짜장면' in 음식메뉴:
    print("짜장면이요")
if '짬뽕' in 음식메뉴:
    print("짬뽕드세요")
else:
    print("오늘 굶으세요")

짜장면이요
짬뽕드세요


In [71]:
음식메뉴 = ['짜장면','짬뽕']
if '짜장면' in 음식메뉴:
    print("짜장면이요")
elif '짬뽕' in 음식메뉴:
    print("짬뽕드세요")
else:
    print("오늘 굶으세요")

짜장면이요


## 반복문(for)

In [72]:
# 반복문은 똑같은 작업을 반복해서 수행하기 위한 제어문.
for i in ['짜장면','짬뽕','군만두']:
    print(i)

짜장면
짬뽕
군만두


In [73]:
음식메뉴=['짜장면','짬뽕','군만두']
for i in 음식메뉴:
    print(i)

짜장면
짬뽕
군만두
